// scripts/deploy.js
const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log("Network:", hre.network.name);
  console.log("Deploying Upload contract...");

  // Get contract and deploy it
  const Upload = await hre.ethers.getContractFactory("Upload");
  const upload = await Upload.deploy();

  await upload.deployed();
  console.log("Upload contract deployed to:", upload.address);

  // Save the address to frontend
  const clientPath = path.join(__dirname, "..", "client", "src");
  const contractAddressFile = path.join(clientPath, "contractAddress.js");

  const fileContent = `// Auto-generated by scripts/deploy.js
const contractAddress = "${upload.address}";
export default contractAddress;
`;

  try {
    fs.writeFileSync(contractAddressFile, fileContent, { encoding: "utf8" });
    console.log(`✅ Saved contract address to: ${contractAddressFile}`);
  } catch (err) {
    console.warn("⚠️ Failed to write contract address file:", err);
    console.warn("You can still copy the address above manually.");
  }
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
